<a href="https://colab.research.google.com/github/Elwing-Chou/ximen0624/blob/main/5_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

講義如果寫(tensorflow 1.x)

from keras.....

你全部改成(tensorflow 2.x)

from tensorflow.keras

In [24]:
from tensorflow.keras.datasets import mnist
# ((訓練圖片, 答案), (側視圖片, 答案))
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [25]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [26]:
# 灰階圖片 0(黑) - 255(白)
import pandas as pd
pd.DataFrame(x_train[0])

0   1   2   3    4    5    6    7    8    9   ...   18   19   20   21   22   23  24  25  26  27
0    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
1    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
2    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
3    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
4    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
5    0   0   0   0    0    0    0    0    0    0  ...  175   26  166  255  247  127   0   0   0   0
6    0   0   0   0    0    0    0    0   30   36  ...  225  172  253  242  195   64   0   0   0   0
7    0   0   0   0    0    0    0   49  238  253  ...   93   82   82   56   39    0   0   0   0   0
8    0   0   0   0    0    0    0   18  219  253  ...    0    0    0    0    0    0   0   0   0   0
9    0   0   0   0    0    0    0    0   80  156  ...    0    0    0    0    0    0   0   0   0   0
10   0   0   0   0    0    0    0    0    0   14  ...    0    0    0    0    0    0   0   0   0   0
11   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
12   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
13   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
14   0   0   0   0    0    0    0    0    0    0  ...   25    0    0    0    0    0   0   0   0   0
15   0   0   0   0    0    0    0    0    0    0  ...  150   27    0    0    0    0   0   0   0   0
16   0   0   0   0    0    0    0    0    0    0  ...  253  187    0    0    0    0   0   0   0   0
17   0   0   0   0    0    0    0    0    0    0  ...  253  249   64    0    0    0   0   0   0   0
18   0   0   0   0    0    0    0    0    0    0  ...  253  207    2    0    0    0   0   0   0   0
19   0   0   0   0    0    0    0    0    0    0  ...  250  182    0    0    0    0   0   0   0   0
20   0   0   0   0    0    0    0    0    0    0  ...   78    0    0    0    0    0   0   0   0   0
21   0   0   0   0    0    0    0    0   23   66  ...    0    0    0    0    0    0   0   0   0   0
22   0   0   0   0    0    0   18  171  219  253  ...    0    0    0    0    0    0   0   0   0   0
23   0   0   0   0   55  172  226  253  253  253  ...    0    0    0    0    0    0   0   0   0   0
24   0   0   0   0  136  253  253  253  212  135  ...    0    0    0    0    0    0   0   0   0   0
25   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
26   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
27   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0

[28 rows x 28 columns]

會有個正常現象叫做 梯度消失現象(越遠的參數看到的斜率越靠近0->根本不調整) 那我們為了去減緩這個現象 所以把sigmoid(m=0-0.25) -> relu(m=0或1) 只要是1那段 那就是不打折

In [27]:
# model有兩種方式 Sequential(堆疊)  Model(複雜)
from tensorflow.keras.models import Sequential
# Dense: 全連接層(fully-connected)
from tensorflow.keras.layers import Dense

layers = [
    # 784 * 64 + 64(bias)
    # !! sigmoid -> relu
    Dense(64, activation="relu", input_dim=784),
    # 標準化(加起來=1)的sigmoid -> softmax
    # 係數 64 * 10 + 10(bias)
    Dense(10, activation="softmax")
]
model = Sequential(layers)
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 64)                50240     
                                                                 
 dense_5 (Dense)             (None, 10)                650       
                                                                 
Total params: 50890 (198.79 KB)
Trainable params: 50890 (198.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
from tensorflow.keras.losses import CategoricalCrossentropy
model.compile(loss=CategoricalCrossentropy(), metrics=["accuracy"])

In [29]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [30]:
from tensorflow.keras.utils import to_categorical
y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)
print(y_train[0])
print(y_train_onehot[0])

5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [31]:
# 其實係數不是完全隨機, 他是在某個範圍作隨機
# 其實變相要求你的輸入應該要落在某個範圍, tensorflow希望你的輸入落在0~1或者-1~1
x_train_scaled = x_train.reshape(60000, 784) / 255.0
x_test_scaled = x_test.reshape(10000, 784) / 255.0

1. 沒做任何改動: 60 epochs
2. mse->cross entropy: 30 epochs
3. sigmoid->relu: 12 epochs

In [32]:
# batch_size: 看了多少筆才更新一次模型參數
# epochs: 整份資料要看幾round
# !!! 究竟是幾round??? 我們不會無限訓練下去(當然loss會越來越小)->過擬和
# 跟機器學習依樣, 你要準備一份他沒看過的, 來檢視現在的擬和程度
# batch=100 vali=0.1  1個epoch做了幾次模型更新: 54000 / 100 = 540
# 擬要看validation loss來決定訓練多少個epochs
# verbose: 印log程度 0(quiet) 1(bar) 2(沒有bar)
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ModelCheckpoint("mnist.h5", save_best_only=True)
]

model.fit(x_train_scaled,
     y_train_onehot,
     batch_size=100,
     epochs=200,
     validation_split=0.1,
     verbose=2,
     callbacks=callbacks)

Epoch 1/200
540/540 - 2s - loss: 0.3876 - accuracy: 0.8964 - val_loss: 0.1827 - val_accuracy: 0.9510 - 2s/epoch - 4ms/step
Epoch 2/200


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


540/540 - 1s - loss: 0.2007 - accuracy: 0.9431 - val_loss: 0.1490 - val_accuracy: 0.9593 - 1s/epoch - 3ms/step
Epoch 3/200
540/540 - 1s - loss: 0.1537 - accuracy: 0.9561 - val_loss: 0.1202 - val_accuracy: 0.9678 - 1s/epoch - 3ms/step
Epoch 4/200
540/540 - 1s - loss: 0.1263 - accuracy: 0.9636 - val_loss: 0.1086 - val_accuracy: 0.9707 - 1s/epoch - 3ms/step
Epoch 5/200
540/540 - 2s - loss: 0.1071 - accuracy: 0.9695 - val_loss: 0.1026 - val_accuracy: 0.9718 - 2s/epoch - 4ms/step
Epoch 6/200
540/540 - 2s - loss: 0.0934 - accuracy: 0.9726 - val_loss: 0.0928 - val_accuracy: 0.9750 - 2s/epoch - 4ms/step
Epoch 7/200
540/540 - 1s - loss: 0.0828 - accuracy: 0.9761 - val_loss: 0.0916 - val_accuracy: 0.9762 - 1s/epoch - 2ms/step
Epoch 8/200
540/540 - 1s - loss: 0.0734 - accuracy: 0.9787 - val_loss: 0.0873 - val_accuracy: 0.9738 - 1s/epoch - 2ms/step
Epoch 9/200
540/540 - 1s - loss: 0.0662 - accuracy: 0.9810 - val_loss: 0.0888 - val_accuracy: 0.9747 - 1s/epoch - 2ms/step
Epoch 10/200
540/540 - 1s - 

In [33]:
# Demo argmax(之前的idxmax)
# axis=0: 直行的最大值 axis=1: 橫列最大值的位置
import numpy as np
np.array([
    [1, 2],
    [3, 4],
    [5, 6]
]).argmax(axis=1)

array([1, 1, 1])

In [34]:
model.evaluate(x_test_scaled, y_test_onehot)

313/313 [==============================] - 1s 2ms/step - loss: 0.0850 - accuracy: 0.9746


[0.08500059694051743, 0.9746000170707703]

In [35]:
pre = model.predict(x_test_scaled).argmax(axis=1)
pre

313/313 [==============================] - 1s 2ms/step


array([7, 2, 1, ..., 4, 5, 6])